version: '3.4'

services:
  portfoliotrackerserver:
    container_name: portfoliotracker-app
    image: ${DOCKER_REGISTRY-}portfoliotrackerserver
    build:
      context: .
      dockerfile: PortfolioTrackerServer/Dockerfile
    ports:
      - "7207:443"
      - "8081:80" 
    depends_on: 
      - portfoliotracker-db
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "7207"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    deploy:
      resources:
        limits:
          cpus: '0.5'  
          memory: 512M


  portfoliotracker-db:
    container_name: portfoliotracker-db
    image: portfoliotracker-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD_FILE: /run/secrets/db-secrets
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/lib/mssql/data
    secrets:
      - db-secrets


volumes:
    db-data:
  
secrets:
  db-secrets:
    file: ./db-secrets.txt
